export const MODEL_CATALOG = [
  { provider: "Anthropic", label: "Claude Haiku 4.5", id: "anthropic/claude-haiku-4.5", multiplier: 1.3 },
  { provider: "Anthropic", label: "Claude Opus 4.5", id: "anthropic/claude-opus-4.5", multiplier: 12.0 },
  { provider: "Anthropic", label: "Claude Opus 4.6", id: "anthropic/claude-opus-4.6", multiplier: 12.0 },
  { provider: "Anthropic", label: "Claude Opus 4.7", id: "anthropic/claude-opus-4.7", multiplier: 12.0 },
  { provider: "Anthropic", label: "Claude Opus 4.8", id: "anthropic/claude-opus-4.8", multiplier: 12.0 },
  { provider: "Anthropic", label: "Claude Sonnet 4.5", id: "anthropic/claude-sonnet-4.5", multiplier: 6.0 },
  { provider: "Anthropic", label: "Claude Sonnet 4.6", id: "anthropic/claude-sonnet-4.6", multiplier: 6.0 },
  { provider: "Anthropic", label: "Claude Sonnet 5", id: "anthropic/claude-sonnet-5", multiplier: 4.0 },
  { provider: "DeepSeek", label: "DeepSeek Chat V3.1", id: "deepseek/deepseek-chat-v3.1", multiplier: 0.8 },
  { provider: "DeepSeek", label: "DeepSeek R1 0528", id: "deepseek/deepseek-r1-0528", multiplier: 0.8 },
  { provider: "DeepSeek", label: "DeepSeek V3.1", id: "deepseek/deepseek-v3.1", multiplier: 0.8 },
  { provider: "DeepSeek", label: "DeepSeek V3.1 Terminus", id: "deepseek/deepseek-v3.1-terminus", multiplier: 0.8 },
  { provider: "DeepSeek", label: "DeepSeek V3.2", id: "deepseek/deepseek-v3.2", multiplier: 0.5 },
  { provider: "DeepSeek", label: "DeepSeek V4 Flash", id: "deepseek/deepseek-v4-flash", multiplier: 0.5 },
  { provider: "DeepSeek", label: "DeepSeek V4 Pro", id: "deepseek/deepseek-v4-pro", multiplier: 0.7 },
  { provider: "Google", label: "Gemini 2.5 Pro", id: "google/gemini-2.5-pro", multiplier: 4.0 },
  { provider: "Google", label: "Gemini 3 Flash Preview", id: "google/gemini-3-flash-preview", multiplier: 1.5 },
  { provider: "Google", label: "Gemini 3 Pro Image", id: "google/gemini-3-pro-image", multiplier: 25.0 },
  { provider: "Google", label: "Gemini 3.1 Flash Image Preview", id: "google/gemini-3.1-flash-image-preview", multiplier: 17.5 },
  { provider: "Google", label: "Gemini 3.1 Flash Lite", id: "google/gemini-3.1-flash-lite", multiplier: 0.5 },
  { provider: "Google", label: "Gemini 3.1 Flash Lite Image", id: "google/gemini-3.1-flash-lite-image", multiplier: 8.8 },
  { provider: "Google", label: "Gemini 3.1 Pro Preview", id: "google/gemini-3.1-pro-preview", multiplier: 5.0 },
  { provider: "Google", label: "Gemini 3.5 Flash", id: "google/gemini-3.5-flash", multiplier: 3.0 },
  { provider: "Google", label: "Gemma 4 26b A4b It", id: "google/gemma-4-26b-a4b-it", multiplier: 0.7 },
  { provider: "Google", label: "Gemma 4 31b It", id: "google/gemma-4-31b-it", multiplier: 0.7 },
  { provider: "MiniMax", label: "MiniMax M2.5", id: "minimax/minimax-m2.5", multiplier: 1.0 },
  { provider: "MiniMax", label: "MiniMax M2.7", id: "minimax/minimax-m2.7", multiplier: 1.0 },
  { provider: "MiniMax", label: "MiniMax M3", id: "minimax/minimax-m3", multiplier: 1.0 },
  { provider: "Moonshot", label: "Kimi K2.5", id: "moonshotai/kimi-k2.5", multiplier: 1.0 },
  { provider: "Moonshot", label: "Kimi K2.6", id: "moonshotai/kimi-k2.6", multiplier: 1.5 },
  { provider: "Moonshot", label: "Kimi K2.7 Code", id: "moonshotai/kimi-k2.7-code", multiplier: 1.6 },
  { provider: "Moonshot", label: "Kimi K2.7 Code Highspeed", id: "moonshotai/kimi-k2.7-code-highspeed", multiplier: 3.3 },
  { provider: "NVIDIA", label: "Nemotron 3 Ultra", id: "nvidia/nemotron-3-ultra", multiplier: 0.0 },
  { provider: "OpenAI", label: "GPT-5", id: "openai/gpt-5", multiplier: 1.8 },
  { provider: "OpenAI", label: "GPT-5 Chat", id: "openai/gpt-5-chat", multiplier: 1.8 },
  { provider: "OpenAI", label: "GPT-5.2", id: "openai/gpt-5.2", multiplier: 2.0 },
  { provider: "OpenAI", label: "GPT-5.2 Chat", id: "openai/gpt-5.2-chat", multiplier: 2.0 },
  { provider: "OpenAI", label: "GPT-5.3 Chat", id: "openai/gpt-5.3-chat", multiplier: 2.0 },
  { provider: "OpenAI", label: "GPT-5.3 Codex", id: "openai/gpt-5.3-codex", multiplier: 2.0 },
  { provider: "OpenAI", label: "GPT-5.4", id: "openai/gpt-5.4", multiplier: 2.0 },
  { provider: "OpenAI", label: "GPT-5.4 Mini", id: "openai/gpt-5.4-mini", multiplier: 0.8 },
  { provider: "OpenAI", label: "GPT-5.4 Nano", id: "openai/gpt-5.4-nano", multiplier: 0.5 },
  { provider: "OpenAI", label: "GPT-5.5", id: "openai/gpt-5.5", multiplier: 5.5 },
  { provider: "OpenAI", label: "GPT Image 1.5", id: "openai/gpt-image-1.5", multiplier: 30.0 },
  { provider: "OpenAI", label: "GPT Image 2", id: "openai/gpt-image-2", multiplier: 27.5 },
  { provider: "Perplexity", label: "Sonar", id: "perplexity/sonar", multiplier: 1.3 },
  { provider: "Perplexity", label: "Sonar Pro", id: "perplexity/sonar-pro", multiplier: 4.8 },
  { provider: "Perplexity", label: "Sonar Reasoning Pro", id: "perplexity/sonar-reasoning-pro", multiplier: 3.3 },
  { provider: "Qwen", label: "Qwen 3.6 Max", id: "qwen/qwen-3.6-max", multiplier: 2.0 },
  { provider: "Qwen", label: "Qwen 3.6 Plus", id: "qwen/qwen3.6-plus", multiplier: 1.5 },
  { provider: "Qwen", label: "Qwen 3.7 Max", id: "qwen/qwen3.7-max", multiplier: 1.8 },
  { provider: "Qwen", label: "Qwen 3.7 Plus", id: "qwen/qwen3.7-plus", multiplier: 1.0 },
  { provider: "Sakana", label: "Fugu Ultra", id: "sakana/fugu-ultra", multiplier: 15.0 },
  { provider: "Xiaomi", label: "Mimo V2 Pro", id: "xiaomi/mimo-v2-pro", multiplier: 1.8 },
  { provider: "Xiaomi", label: "Mimo V2.5", id: "xiaomi/mimo-v2.5", multiplier: 0.5 },
  { provider: "Xiaomi", label: "Mimo V2.5 Pro", id: "xiaomi/mimo-v2.5-pro", multiplier: 0.7 },
  { provider: "Z-AI", label: "Glm 4.6", id: "z-ai/glm-4.6", multiplier: 1.5 },
  { provider: "Z-AI", label: "Glm 4.7", id: "z-ai/glm-4.7", multiplier: 1.5 },
  { provider: "Z-AI", label: "Glm 5", id: "z-ai/glm-5", multiplier: 2.0 },
  { provider: "Z-AI", label: "Glm 5.1", id: "z-ai/glm-5.1", multiplier: 2.0 },
  { provider: "Z-AI", label: "Glm 5.2", id: "z-ai/glm-5.2", multiplier: 2.0 },
  { provider: "Z-AI", label: "Glm 5.2 Fast", id: "z-ai/glm-5.2-fast", multiplier: 2.0 },
  { provider: "xAI", label: "Grok 4.1 Fast", id: "x-ai/grok-4.1-fast", multiplier: 0.7 },
  { provider: "xAI", label: "Grok 4.20", id: "x-ai/grok-4.20", multiplier: 1.5 },
  { provider: "xAI", label: "Grok 4.3", id: "x-ai/grok-4.3", multiplier: 1.5 },
  { provider: "xAI", label: "Grok Build 0.1", id: "x-ai/grok-build-0.1", multiplier: 1.0 },
] as const;
